[package]
name = "libxcrypt"
version = "4.4.36"
author = "besser82"
type = "curl"
src = ["https://github.com/besser82/libxcrypt/releases/download/v4.4.36/libxcrypt-4.4.36.tar.xz"]

[build]
compile = [
        "cd libxcrypt-4.4.26.tar.xz",
        "./configure --prefix=/usr --enable-hashes=strong,glibc --enable-obsolete-api=no --disable-static  --disable-failure-tokens",
        "make"
	]

install = [
        "make install"
]