[package]
name = "ffmpeg"
version = "7.1.1"
author = "FFmpeg Team"
type = "curl"
src = [
    "https://ffmpeg.org/releases/ffmpeg-7.1.1.tar.xz",
    "https://www.linuxfromscratch.org/patches/blfs/svn/ffmpeg-7.1.1-chromium_method-1.patch"
]

[build]
compile = [
    "patch -Np1 -i ../ffmpeg-7.1.1-chromium_method-1.patch",
    "./configure --prefix=/usr \
                --enable-gpl \
                --enable-version3 \
                --enable-nonfree \
                --disable-static \
                --enable-shared \
                --disable-debug \
                --enable-libaom \
                --enable-libass \
                --enable-libfdk-aac \
                --enable-libfreetype \
                --enable-libmp3lame \
                --enable-libopus \
                --enable-libvorbis \
                --enable-libvpx \
                --enable-libx264 \
                --enable-libx265 \
                --enable-openssl \
                --ignore-tests=enhanced-flv-av1 \
                --docdir=/usr/share/doc/ffmpeg-7.1.1",
    "make",
    "gcc tools/qt-faststart.c -o tools/qt-faststart"
]

install = [
    "make install",
    "install -v -m755 tools/qt-faststart /usr/bin",
    "install -v -m755 -d /usr/share/doc/ffmpeg-7.1.1",
    "install -v -m644 doc/*.txt /usr/share/doc/ffmpeg-7.1.1"
]

[dependencies]
libaom = "3.12.0"
libass = "0.17.3"
fdk-aac = "2.0.3"
freetype = "2.13.3"
lame = "3.100"
libvorbis = "1.3.7"
libvpx = "1.15.0"
opus = "1.5.2"
x264 = "20250212"
x265 = "4.1"
nasm = "2.16.03"
