[package]
name = "file"
version = "5.45"
author = "file"
type = "curl"
src = ["https://astron.com/pub/file/file-5.45.tar.gz"]

[build]

compile = [

    "./configure --prefix=/usr",
    "make"
]

install = [
    "make install"
]
