[package]

name = "gcc"
version = "14.2.0"
author = "GNU"
type = "curl"
src = ["https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.xz"]

[build]

compile = [
"wget https://github.com/LearnixOS/lxos-repo/blob/main/core/gcc/files/x86_64.sh | /bin/sh",
"mkdir build",
"cd build",
"../configure --prefix=/usr LD=ld --enable-languages=c,c++ --enable-default-pie   --enable-default-ssp --enable-host-pie --disable-multilib --disable-bootstrap   --disable-fixincludes --with-system-zlib",
"make"
]

install = [
"make install",
"chown -v -R root:root /usr/lib/gcc/$(gcc -dumpmachine)/14.2.0/include{,-fixed}",
"ln -svr /usr/bin/cpp /usr/lib",
"ln -sv gcc.1 /usr/share/man/man1/cc.1",
"ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/14.2.0/liblto_plugin.so /usr/lib/bfd-plugins/",
"mkdir -pv /usr/share/gdb/auto-load/usr/lib",
"mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib"
]
