[package]

name = "iproute2"
version = "6.10.0"
author = "saladtoes"
type = "curl"
src = ["https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-6.10.0.tar.xz"],

[build]

compile = [
        "sed -i /ARPD/d Makefile",
        "rm -fv man/man8/arpd.8",
        "make NETNS_RUN_DIR=/run/netns",
]

install = [
        "make SBINDIR=/usr/sbin install",
        "mkdir -pv             /usr/share/doc/iproute2-6.10.0",
        "cp -v COPYING README* /usr/share/doc/iproute2-6.10.0"
]
