
[package]
name = "markupsafe"
version = "2.1.5"
author = "MarkupSafe"
type = "curl"
src = ["https://pypi.org/packages/source/M/MarkupSafe/MarkupSafe-2.1.5.tar.gz"]

[build]
compile = [
"pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD",
]
install = [
        "pip3 install --no-index --no-user --find-links dist Markupsafe"
]
