    

[package]

name = "openssl"
version = "3.3.1"
author = "saladtoes"
type = "curl"
src = ["https://www.openssl.org/source/openssl-3.3.1.tar.gz"]

[build]

compile = [
        "./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic",
        "make",
        "sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile"
]

install = [
        "make MANSUFFIX=ssl install",
        "mv -v /usr/share/doc/openssl /usr/share/doc/openssl-3.3.1",
        "cp -vfr doc/* /usr/share/doc/openssl-3.3.1"
]

