[package]

name = "bash"
version = "5.2.32"
author = "saladtoes"
type = "curl"
src = ["https://ftp.gnu.org/gnu/bash/bash-5.2.32.tar.gz"]

[build]
compile = [
	"./configure --prefix=/usr --without-bash-malloc --with-installed-readline bash_cv_strtold_broken=no --docdir=/usr/share/doc/bash-5.2.32",
	"make"
]

install = [
	"make install"
]
