[package]

name = "gdbm"
version = "1.24"
author = "GNU"
type = "curl"
src = ["https://ftp.gnu.org/gnu/gdbm/gdbm-1.24.tar.gz"]

[build]

compile = [
        "./configure --prefix=/usr --disable-static --enable-libgdbm-compat",
        "make",
]

install = [
        "make install"
]
