[package]
name = "qrencode"
version = "4.1.1"
author = "Kentaro Fukuchi"
type = "curl"
src = ["https://fukuchi.org/works/qrencode/qrencode-4.1.1.tar.bz2"]

[build]
compile = [
    "./configure --prefix=/usr",
    "make"
]

[install]
install = [
    "make install"
]
