[package]

name = "iana-etc"
version = "20240806"
author = "Mic92"
type = "curl"
src = ["https://github.com/Mic92/iana-etc/releases/download/20240806/iana-etc-20240806.tar.gz"]

[build]

compile = [
]

install = [
        "cd iana-etc-20240806",
        "cp services protocols /etc"
]
