[package]

name = "efivar"
version = "39"
author = "saladtoes"
type = "curl"
src = ["https://github.com/rhboot/efivar/archive/39/efivar-39.tar.gz"]

[build]

compile = [
"make"
]

install = [
        "make install LIBDIR=/usr/lib"
]


