[package] 
name = "zstd" 
version = "1.5.6"
author = "saladtoes"
type = "curl"
src = ["https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-1.5.6.tar.gz"]

[build]
compile = [
        "make prefix=/usr"
]
install = [
"make prefix=/usr install",
"rm -v /usr/lib/libzstd.a"
]
