[package]
name = "pciutils"
version = "3.10.0"
author = "Martin Mares"
license = "GPL-2.0"
type = "curl"
src = ["https://mj.ucw.cz/download/linux/pci/pciutils-3.10.0.tar.gz"]

[build]
compile = [
    "make PREFIX=/usr",
    "make PREFIX=/usr install"
]
install = []

[dependencies]
zlib = "*"
