    
[package]

name = "setuptools"
version = "72.2.0"
author = "Pypi"
type = "curl"
src = ["https://pypi.org/packages/source/s/setuptools/setuptools-72.2.0.tar.gz"]

[build]

compile = [
        "pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD",
]

install = [
        "pip3 install --no-index --find-links dist setuptools"
]

