[package]
name = "busybox"
version = "1.37.0"
author = "BusyBox Team"
type = "curl"
src = ["https://busybox.net/downloads/busybox-1.37.0.tar.bz2"]

[patches]
patches = []

[build]
compile = [
    "tar xf busybox-1.37.0.tar.bz2",
    "cd busybox-1.37.0",
    "make defconfig",                     # Use default config for a minimal setup
    "sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config",  # Build statically for standalone binary
    "make"
]

install = [
    "make CONFIG_PREFIX=/usr install",    # Install to /usr
    "ln -sf /usr/bin/busybox /bin/sh"     # Link sh to busybox
]
