[package]
name = "alsa-lib"
version = "1.2.13"
author = "alsa"
type = "curl"
src = ["https://www.alsa-project.org/files/pub/lib/alsa-ucm-conf-1.2.13.tar.bz2"]

[build]
compile = [
    "./configure",
	"make"
]

install = [
        "make install",
	"tar -C /usr/share/alsa --strip-components=1 -xf ../alsa-ucm-conf-1.2.13.tar.bz2"
]


