[package]
name = "libtiff"
version = "4.4.0"
author = "libtiff Developers"
type = "curl"
src = ["https://download.osgeo.org/libtiff/tiff-4.4.0.tar.gz"]

[build]
compile = [
    "./configure --prefix=/usr",
    "make"
]
install = [
    "make install"
]

[dependencies]
zlib = "*"
jpeg = "*"

