[package]
name = "btop++"
version = "1.4.0"
author = "aristocratos"
type = "curl"
src = ["https://github.com/aristocratos/btop/archive/refs/tags/v1.4.0.tar.gz"]

[build]
compile = [
    "cmake -B build",
    "cmake --build build"
]

install = [
    "sudo cmake --install build"
]
