[package]

name = "dejagnu"
version = "1.6.3"
author = "saladtoes"
type = "curl"
src = ["https://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.3.tar.gz"]

[build]

compile = [
        "mkdir -v build",
        "cd build",
        "../configure --prefix=/usr",
        "makeinfo --html --no-split -o doc/dejagnu.html ../doc/dejagnu.texi",
        "makeinfo --plaintext       -o doc/dejagnu.txt  ../doc/dejagnu.texi"
]

install = [

        "make install",
        "install -v -dm755  /usr/share/doc/dejagnu-1.6.3",
        "install -v -m644   doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-1.6.3"
]


