[package]
name = "xterm"
version = "397"
author = "invisible-mirror"
type = "curl"
src = ["https://invisible-mirror.net/archives/xterm/xterm-397.tgz"]

dependencies = [
    "luit-20240910",
    "dejavu-fonts-2.37",
    "emacs-30.1",
    "pcre2-10.45",
    "valgrind-3.24.0",
    "man2html-1.6g"
]

[build]
compile = [
    "sed -i '/v0/{n;s/new:/new:kb=^?:/}' termcap",
    "printf '\tkbs=\\177,\n' >> terminfo",
    "TERMINFO=/usr/share/terminfo ./configure $XORG_CONFIG --with-app-defaults=/etc/X11/app-defaults",
    "make"
]

install = [
    "make install",
    "mkdir -pv /usr/share/applications",
    "cp -v *.desktop /usr/share/applications/"
]
