
[package]

name = "tar"
version = "1.25"
author = "GNU"
type = "curl"
src = ["https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz"]

[build]

compile = [
        "FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr",
        "make"
]

install = [
        "make install",
        "make -C doc install-html docdir=/usr/share/doc/tar-1.35"
]

