[package]
name = "IO-String"
version = "1.08"
author = "GAAS"
type = "curl"
src = ["https://www.cpan.org/authors/id/G/GA/GAAS/IO-String-1.08.tar.gz"]

[build]
compile = ["perl Makefile.PL", "make", "make test"]

[install]
install = ["make install"]

[dependencies]
# No required dependencies listed
