[package]
name = "libwww-perl"
version = "6.78"
author = "OALDERS"
type = "curl"
src = ["https://www.cpan.org/authors/id/O/OA/OALDERS/libwww-perl-6.78.tar.gz"]

[build]
compile = ["perl Makefile.PL", "make", "make test"]

[install]
install = ["make install"]

[dependencies]
"File-Listing" = "6.16"
"HTTP-CookieJar" = "0.014"
"HTTP-Cookies" = "6.11"
"HTTP-Daemon" = "6.16"
"HTTP-Negotiate" = "6.01"
"HTML-Parser" = "3.83"
"Net-HTTP" = "6.23"
"Try-Tiny" = "0.32"
"WWW-RobotRules" = "6.02"
