[package]
name = "List-MoreUtils"
version = "0.430"
author = "REHSACK"
type = "curl"
src = ["https://www.cpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-0.430.tar.gz"]

[build]
compile = ["perl Makefile.PL", "make", "make test"]

[install]
install = ["make install"]

[dependencies]
"Exporter-Tiny" = "1.006002"
"List-MoreUtils-XS" = "0.430"
