[package]
name = "Net-DNS"
version = "1.50"
author = "NLNETLABS"
type = "curl"
src = ["https://www.cpan.org/authors/id/N/NL/NLNETLABS/Net-DNS-1.50.tar.gz"]

[build]
compile = ["perl Makefile.PL", "make", "make test"]

[install]
install = ["make install"]

[dependencies]
# No required dependencies listed
