[package]
name = "Sort-Key"
version = "1.33"
author = "SALVA"
type = "curl"
src = ["https://www.cpan.org/authors/id/S/SA/SALVA/Sort-Key-1.33.tar.gz"]

[build]
compile = ["perl Makefile.PL", "make", "make test"]

[install]
install = ["make install"]

[dependencies]
# No required dependencies listed
