[package]
name = "Test-Command"
version = "0.11"
author = "DANBOO"
type = "curl"
src = ["https://www.cpan.org/authors/id/D/DA/DANBOO/Test-Command-0.11.tar.gz"]

[build]
compile = ["perl Makefile.PL", "make", "make test"]

[install]
install = ["make install"]

[dependencies]
# No required dependencies listed
