[package]
name = "qca"
version = "2.3.10"
author = "KDE Community"
type = "curl"
src = ["https://download.kde.org/stable/qca/2.3.10/qca-2.3.10.tar.xz"]

[build]
compile = [
    "sed -i 's@cert.pem@certs/ca-bundle.crt@' CMakeLists.txt",
    "mkdir build && cd build",
    "cmake -D CMAKE_INSTALL_PREFIX=$QT6DIR -D CMAKE_BUILD_TYPE=Release -D QT6=ON -D QCA_INSTALL_IN_QT_PREFIX=ON -D QCA_MAN_INSTALL_DIR:PATH=/usr/share/man ..",
    "make"
]

[install]
install = [
    "make install"
]

[dependencies]
make-ca = "1.15"
cmake = "3.31.6"
qt6 = "6.8.3"
which = "2.23"
