[package]
name = "libgif"
version = "5.2.1"
author = "GIFLIB Developers"
type = "curl"
src = ["https://sourceforge.net/projects/giflib/files/giflib-5.2.1.tar.gz"]

[build]
compile = [
    "make"
]
install = [
    "make install PREFIX=/usr"
]

[dependencies]

