[package]
name = "boost"
version = "1.87.0"
author = "Boost Community"
type = "curl"
src = ["https://github.com/boostorg/boost/releases/download/boost-1.87.0/boost-1.87.0-b2-nodocs.tar.xz"]

[build]
compile = [
    "case $(uname -m) in i?86) sed -e 's/defined(__MINGW32__)/& || defined(__i386__)/' -i ./libs/stacktrace/src/exception_headers.h ;; esac",
    "./bootstrap.sh --prefix=/usr --with-python=python3",
    "./b2 stage -j$(nproc) threading=multi link=shared"
]

install = [
    "rm -rf /usr/lib/cmake/[Bb]oost*",
    "./b2 install threading=multi link=shared"
]

[dependencies]
which = "2.23"
# Optional dependencies (commented out as they are not required):
# icu = "77.1"
# numpy = "2.2.4"
# openmpi = "*"
