[package]
name = "pango"
version = "1.56.3"
author = "GNOME Project"
type = "curl"
src = ["https://download.gnome.org/sources/pango/1.56/pango-1.56.3.tar.xz"]

[build]
compile = [
    "mkdir build",
    "cd build",
    "meson setup --prefix=/usr \
                --buildtype=release \
                --wrap-mode=nofallback \
                -D introspection=enabled ..",
    "ninja"
]

install = [
    "ninja install"
]

[dependencies]
fontconfig = "*"
freetype = "*"
harfbuzz = "*"
fribidi = "*"
glib = "*"

