[package]

name = "vim"
version = "9.1.0660"
author = "Bram Moolenaar"
type = "curl"
src = ["https://github.com/vim/vim/archive/v9.1.0660/vim-9.1.0660.tar.gz"]

[build]

compile = [
        "echo `#define SYS_VIMRC_FILE '/etc/vimrc'` >> src/feature.h",
        "./configure --prefix=/usr",
        "make",
]

install = [
        "make install",
        "ln -sv vim /usr/bin/vi",
        "wget https://raw.githubusercontent.com/LearnixOS/lxos-repo/refs/heads/main/core/vim/files/symlinks.sh | /bin/sh",
        "ln -sv ../vim/vim91/doc /usr/share/doc/vim-9.1.0660",
        "wget https://raw.githubusercontent.com/LearnixOS/lxos-repo/refs/heads/main/core/vim/files/vimrc > /etc/vimrc"
]

