[package]
name = "bottom"
version = "0.10.2"
author = "Clement Tsang"
type = "cargo"
src = ["https://github.com/ClementTsang/bottom/releases/download/0.10.2/bottom_aarch64-unknown-linux-gnu.tar.gz"]

[build]
compile = [
    "rustup update stable", 
    "cargo install bottom --locked"
]

install = [
    "cargo install bottom --locked"
]

