[package]
name = "extra-cmake-modules"
version = "6.11.0"
author = "KDE Community"
type = "curl"
src = ["https://download.kde.org/stable/frameworks/6.11/extra-cmake-modules-6.11.0.tar.xz"]

[build]
compile = [
    "sed -i '/\"lib64\"/s/64//' kde-modules/KDEInstallDirsCommon.cmake",
    "sed -e '/PACKAGE_INIT/i set(SAVE_PACKAGE_PREFIX_DIR \"${PACKAGE_PREFIX_DIR}\")' -e '/^include/a set(PACKAGE_PREFIX_DIR \"${SAVE_PACKAGE_PREFIX_DIR}\")' -i ECMConfig.cmake.in",
    "mkdir build && cd build",
    "cmake -D CMAKE_INSTALL_PREFIX=/usr -D BUILD_WITH_QT6=ON ..",
    "make"
]

install = [
    "make install"
]

[dependencies]
cmake = "3.31.6"
