[package]
name = "fribidi"
version = "1.0.16"
author = "FriBidi Team"
type = "curl"
src = ["https://github.com/fribidi/fribidi/releases/download/v1.0.16/fribidi-1.0.16.tar.xz"]

[build]
compile = [
    "mkdir build && cd build",
    "meson setup --prefix=/usr --buildtype=release ..",
    "ninja"
]

install = [
    "ninja install"
]
