[package]

name = "acl"
version = "2.3.2",
author = "saladtoes"
type = "curl"
src = ["https://download.savannah.gnu.org/releases/acl/acl-2.3.2.tar.xz"]

[build]

compile = [
        "cd acl-2.3.2.tar.xz",
        "./configure --prefix=/usr --disable-static  --disable-static",
        "make"
]

install = [
        "make install"
]

