[package]
name = "elogind"
version = "255.17"
author = "elogind"
type = "curl"
src = ["https://github.com/elogind/elogind/archive/v255.17/elogind-255.17.tar.gz"]

[build]
compile = [
		"mkdir build",
		"cd build",
		"meson setup ..                               \
      --prefix=/usr                          \
      --buildtype=release                    \
      -D man=auto                            \
      -D docdir=/usr/share/doc/elogind-255.17 \
      -D cgroup-controller=elogind           \
      -D dev-kvm-mode=0660                   \
      -D dbuspolicydir=/etc/dbus-1/system.d",
		"ninja"
]

install = [
        "ninja install",
        "ln -sfv  libelogind.pc /usr/lib/pkgconfig/libsystemd.pc",
        "ln -sfvn elogind /usr/include/systemd"
]
