[package]
name = "libvorbis"
version = "1.3.7"
author = "Xiph.Org Foundation"
type = "curl"
src = ["https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.xz"]

[build]
compile = [
    "./configure --prefix=/usr --disable-static",
    "make"
]

[install]
install = [
    "make install",
    "install -v -m644 doc/Vorbis* /usr/share/doc/libvorbis-1.3.7"
]

[dependencies]
libogg = "1.3.5"
