[package]

name = "expat"
version = "2.6.2"
author = "expat"
type = "curl"
src = ["https://sourceforge.net/projects/expat/files/expat/2.6.2/expat-2.6.2-RENAMED-VULNERABLE-PLEASE-USE-2.6.4-INSTEAD.tar.xz"]

[build]

compile = [
	"./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/expat-2.6.2",
	"make"
]

install = [

	"make install",
	"install -v -m644 doc/*.{html,css} /usr/share/doc/expat-2.6.2"
]


