[package]
name = "libical"
version = "3.0.20"
author = "libical Project"
type = "curl"
src = ["https://github.com/libical/libical/releases/download/v3.0.20/libical-3.0.20.tar.gz"]

[build]
compile = [
    "mkdir build && cd build",
    "cmake -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_BUILD_TYPE=Release -D SHARED_ONLY=yes -D ICAL_BUILD_DOCS=false -D ICAL_BUILD_EXAMPLES=false -D GOBJECT_INTROSPECTION=true -D ICAL_GLIB_VAPI=true ..",
    "make"
]

[install]
install = [
    "make install"
]

[dependencies]
cmake = "3.31.6"
