[package]
name = "Exo"
version = "4.20.0"
author = "Xfce Devs"
type = "curl"
src = ["https://archive.xfce.org/src/xfce/exo/4.20/exo-4.20.0.tar.bz2"]

[build]
compile = [
    "./configure --prefix=/usr --sysconfdir=/etc",
    "make"
]
install = [
    "make install"
]

[dependencies]
gtk3 = "*"
libxfce4util = "*"

