[package]
name = "libxfce4ui"
version = "4.20.0"
author = "XFCE Devs"
type = "curl"
src = [" https://archive.xfce.org/src/xfce/libxfce4ui/4.20/libxfce4ui-4.20.0.tar.bz2"]


[build]
compile = [
    "./configure --prefix=/usr --sysconfdir=/etc",
    "make"
]

install = [
    "make install"
]

[dependencies]
glib = "*"
vala = "*"
gtk-doc = "*"
glade = "*"
startup-notification = "*"
libgtop = "*"
gtk-3 = "*"
libgudev = "*"
xfconf = "*"
