[package]
name = "xfce4-session"
version = "4.20.0"
author = "Xfce Devs"
type = "curl"
src = ["https://archive.xfce.org/src/xfce/xfce4-session/4.20/xfce4-session-4.20.0.tar.bz2"]

[build]
compile = [
    "./configure --prefix=/usr --sysconfdir=/etc",
    "make"
]
install = [
    "make install"
]

[dependencies]
gtk3 = "*"
libxfce4ui = "*"
libxfce4util = "*"
libsm = "*"
libwnck = "*"
xfconf = "*"

