[package]
name = "libxslt"
version = "1.1.43"
author = "GNOME Project"
type = "curl"
src = ["https://download.gnome.org/sources/libxslt/1.1/libxslt-1.1.43.tar.xz"]

[build]
compile = [
    "./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/libxslt-1.1.43",
    "make"
]

[install]
install = [
    "make install"
]

[dependencies]
libxml2 = "2.13.6"
