[package]
name = "p11-kit"
version = "0.25.5"
author = "p11-glue Project"
type = "curl"
src = ["https://github.com/p11-glue/p11-kit/releases/download/0.25.5/p11-kit-0.25.5.tar.xz"]

[build]
compile = [
    "sed '20,$ d' -i trust/trust-extract-compat",
    "echo '# Copy existing anchor modifications to /etc/ssl/local' >> trust/trust-extract-compat",
    "echo '/usr/libexec/make-ca/copy-trust-modifications' >> trust/trust-extract-compat",
    "echo '' >> trust/trust-extract-compat",
    "echo '# Update trust stores' >> trust/trust-extract-compat",
    "echo '/usr/sbin/make-ca -r' >> trust/trust-extract-compat",
    "mkdir p11-build && cd p11-build",
    "meson setup .. --prefix=/usr --buildtype=release -D trust_paths=/etc/pki/anchors",
    "ninja"
]

[install]
install = [
    "ninja install",
    "ln -sfv /usr/libexec/p11-kit/trust-extract-compat /usr/bin/update-ca-certificates",
    # Configure as NSS replacement
    "ln -sfv ./pkcs11/p11-kit-trust.so /usr/lib/libnssckbi.so"
]
