[package] 
name = "attr"
version = "2.5.2"
author = "GNU"
type = "curl"
src = ["https://download.savannah.gnu.org/releases/attr/attr-2.5.2.tar.gz"]

[build]

compile = [
        "cd attr-2.5.2",
        "./configure --prefix=/usr --disable-static --sysconfdir=/etc --docdir=/usr/share/doc/attr-2.5.2",
        "make"
]

install = [
	"make install"
]
