[package]

name = "linux-firmware"
version = "20250311"
author = "Linus Torvalts"
type = "curl"
src = ["https://web.git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-20250311.tar.gz"]

[build]

install = [
        "rsync -a --chown=root:root ./ /lib/firmware"
]
