[package]
name = "rust"
version = "1.81.0"
type = "script"
src = ["https://sh.rustup.rs"]

[install]
commands = [
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /tmp/rustup.sh",
    "sh /tmp/rustup.sh -y",
    "rm /tmp/rustup.sh",
    "rustup default stable"
]

[uninstall]
commands = [
    "rustup self uninstall -y"
]
