[package]

name = "readline"
version = "8.2.13"
author = "saladtoes"
type = "curl"
src = ["https://ftp.gnu.org/gnu/readline/readline-8.2.13.tar.gz"]

[build]

compile = [
        "sed -i '/MV.*old/d' Makefile.in",
        "sed -i '/{OLDSUFF}/c:' support/shlib-install",
        "sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf",
        "./configure --prefix=/usr --disable-static --with-curses --docdir=/usr/share/doc/readline-8.2.13",
        "make SHLIB_LIBS='-lncursesw'"
]

install = [
        "make SHLIB_LIBS='-lncursesw' install",
        "install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-8.2.13"
]

