[package]

name = "binutils"
version = "2.43.1"
author = "saladtoes"
type = "curl"
src = ["https://sourceware.org/pub/binutils/releases/binutils-2.43.1.tar.xz"]

[build]

compile = [
        "mkdir -v build",
        "cd build",
        "../configure --prefix=/usr --sysconfdir=/etc --enable-gold --enable-ld=default --enable-plugins --enable-shared --disable-werror --enable-64-bit-bfd --enable-new-dtags --with-system-zlib --enable-default-hash-style=gnu",
        "make tooldir=/usr",
]

install = [
        "make tooldir=/usr install",
        "rm -fv /usr/lib/lib{bfd,ctf,ctf-nobfd,gprofng,opcodes,sframe}.a"
]



