[package]

name = "less"
version = "661"
author = "Mark Nudelman"
type = "curl"
src = ["https://www.greenwoodsoftware.com/less/less-661.tar.gz"]

[build]
compile = [
        "./configure --prefix=/usr --sysconfdir=/etc",
        "make"
]
install = [
        "make install"
]
