# xkeyboard-config-2.44
[[package]]
name = "xkeyboard-config"
version = "2.44"
author = "Xorg"
type = "curl"
src = ["https://xorg.freedesktop.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.44.tar.bz2"]

[build]
compile = [
    "./configure --prefix=/usr",
    "make"
]

install = [
    "make install"
]

