[package]

name = "dbus"
version = "1.14.10"
author = "saladtoes"
type = "curl"
src =  ["https://dbus.freedesktop.org/releases/dbus/dbus-1.14.10.tar.xz"]

[build]

compile = [

	"./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --runstatedir=/run  --enable-user-session --disable-static --disable-doxygen-docs --disable-xml-docs --docdir=/usr/share/doc/dbus-1.14.10 --with-system-socket=/run/dbus/system_bus_socket",
	"make"
]

install = [

	"make install",
	"ln -sfv /etc/machine-id /var/lib/dbus"

]

