[package]

name = "xz"
version = "5.6.2"
author = "tukanni"
type = "curl"
src = ["https://github.com//tukaani-project/xz/releases/download/v5.6.2/xz-5.6.2.tar.xz"]

[build]

compile = [
        "./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/xz-5.6.2",
        "make"
]

install = [
        "make install"
]

