    

[package]

name = "pkgconf"
version = "2.3.0"
author = "Pkgconf"
type = "curl"
src = ["https://distfiles.ariadne.space/pkgconf/pkgconf-2.3.0.tar.xz"]

[build]

compile = [
        "./configure --prefix=/usr --disable-static --docdir=/usr/share/doc/pkgconf-2.3.0",
        "make"
]

install = [
        "make install",
        "ln -sv pkgconf   /usr/bin/pkg-config",
        "ln -sv pkgconf.1 /usr/share/man/man1/pkg-config.1"
]

