[package]

name = "bison"
version = "3.8.2"
author = "GNU"
type = "curl"
src = ["https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz"]

[build]

compile = [
	"./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2",
	"make"
]

install = [
	"make install"
]

