[package]
name = "libXcomposite"
version = "0.4.6"
author = "X.Org"
type = "curl"
src = ["https://www.x.org/pub/individual/lib/libXcomposite-0.4.6.tar.xz"]

[build]
compile = ["./configure $XORG_CONFIG --docdir=$XORG_PREFIX/share/doc/libXcomposite-0.4.6", "make"]

[install]
install = ["make install", "/sbin/ldconfig"]

[dependencies]
fontconfig = "2.16.0"
libxcb = "1.17.0"
