
[package]

name = "wheel"
version = "0.44.0"
author = "saladtoes"
type = "curl"
src = ["https://pypi.org/packages/source/w/wheel/wheel-0.44.0.tar.gz"]

[build]

compile = [
        "pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD"
]

install = [

        "pip3 install --no-index --find-links=dist wheel"
]

