[package]
name = "neofetch"
version = "7.1.0"
author = "dylanaraps"
type = "curl"
src = ["https://github.com/dylanaraps/neofetch/archive/refs/tags/7.1.0.tar.gz"]
[build]
compile = [
   ""
]

install = [
    "make install"
]

