[package]

name = "grub-bios"
version = "2.12"
author = "saladtoes"
type = "curl"
src = ["https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz"]

[build]

compile = [
        "unset {C,CPP,CXX,LD}FLAGS",
        "echo depends bli part_gpt > grub-core/extra_deps.lst",
        "./configure --prefix=/usr --sysconfdir=/etc --disable-efiemu --disable-werror",
        "make",
]

install = [
        "make install",
        "mv -v /etc/bash_completion.d/grub /usr/share/bash-completion/completions"
]
