}
[package]

name = "grub-efi"
version = "12.2"
author = "GNU"
type = "curl"
src = ["https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz"]

[build]

compile = [
        "wget https://unifoundry.com/pub/unifont/unifont-15.1.05/font-builds/unifont-15.1.05.pcf.gz",
        "mkdir -pv /usr/share/fonts/unifont ",
        "gunzip -c ../unifont-15.1.05.pcf.gz > /usr/share/fonts/unifont/unifont.pcf",
        "unset {C,CPP,CXX,LD}FLAGS",
        "echo depends bli part_gpt > grub-core/extra_deps.lst",
        "./configure --prefix=/usr --sysconfdir=/etc --disable-efiemu --enable-grub-mkfont --with-platform=efi --target=x86_64 --disable-werror",
        "unset TARGET_CC",
        "make"
]

install = [
        "make install",
        "mv -v /etc/bash_completion.d/grub /usr/share/bash-completion/completions"
]

[extra]

deps = [

"efibootmgr>=18",
"freetype>=2.13.3"
]
