[package]
name = "busybox"
version = "1.37.0"
author = "BusyBox Team"
type = "curl"
src = ["https://busybox.net/downloads/busybox-1.37.0.tar.bz2"]

[build]
compile = [
    "tar xf busybox-1.37.0.tar.bz2",
    "cd busybox-1.37.0",
    "make defconfig",   
    "sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config",
    "make"
]

install = [
    "make CONFIG_PREFIX=/usr install",    # Install to /usr
    "ln -sf /usr/bin/busybox /bin/sh"     # Link sh to busybox
]
