[package]
name = "libaom"
version = "3.12.0"
author = "Alliance for Open Media"
type = "curl"
src = ["https://storage.googleapis.com/aom-releases/libaom-3.12.0.tar.gz"]

[build]
compile = [
    "mkdir aom-build && cd aom-build",
    "cmake -D CMAKE_INSTALL_PREFIX=/usr \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_SHARED_LIBS=1 \
          -D ENABLE_DOCS=no \
          -G Ninja ..",
    "ninja"
]

install = [
    "ninja install",
    "rm -v /usr/lib/libaom.a"
]

[dependencies]
yasm = "1.3.0"
