[package]

name = "flit-core"
version = "3.9.0"
author = "saladtoes"
type = "curl"
src = ["https://pypi.org/packages/source/f/flit-core/flit_core-3.9.0.tar.gz"]

[build]

compile = [
"pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD",
]

install = [
"pip3 install --no-index --no-user --find-links dist flit_core"
]
