[package]

name = "groff"
version = "1.23.0"
author = "GNU"
type = "curl"
src = ["https://ftp.gnu.org/gnu/groff/groff-1.23.0.tar.gz"]

[build]

compile = [
"PAGE=letter ./configure --prefix=/usr",
"make"
]

install = [
        "make install"
]
