[package]

name = "flex"
version = "2.6.4"
author = "saladtoes"
type = "curl"
src = ["https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz"],

[build]

compile = [
        "./configure --prefix=/usr --docdir=/usr/share/doc/flex-2.6.4 --disable-static",
        "make",
]

install = [

        "make install",
        "ln -sv flex   /usr/bin/lex",
        "ln -sv flex.1 /usr/share/man/man1/lex.1"
]
