[package]

name = "expect"
version = "5.45.4"
author = "expect"
type = "curl"
src = ["https://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz"]


[patches]

patches = [
"https://github.com/LearnixOS/lxos-repo/blob/main/core/expect/files/expect-5.45.4-gcc14.1.patch"
]

[build]

compile = [
        "./configure --prefix=/usr --with-tcl=/usr/lib --enable-shared --disable-rpath --mandir=/usr/share/man --with-tclinclude=/usr/include",
        "make"
]

install = [
        "make install",
        "ln -svf expect5.45.4/libexpect5.45.4.so /usr/lib"
]




