[package]
name = "st"
version = "0.9.2"
author = "suckless"
type = "curl"
src = ["https://dl.suckless.org/st/st-0.9.2.tar.gz"]

dependencies = []

[build]
compile = [
    "make"
]

install = [
    "make install"
]
