
[package]

name = "xmlparser"
version = "2.47"
author = "saladtoes"
type = "curl"
src = ["https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.47.tar.gz"]

[build]

compile = [
        "perl Makefile.PL",
        "make"
]

install = [
"make install"
]

