# xorg-server
[[package]]
name = "xorg-server"
version = "21.1.8"
author = "Xorg"
type = "curl"
src = ["https://xorg.freedesktop.org/releases/individual/xserver/xorg-server-21.1.8.tar.xz"]

dependencies = ["xorg-server", "libxcvt", "pixman", "xkeyboard-config", "xorg-fonts"]

[build]
compile = [
    "./configure \",
    "    --prefix=/usr \",
    "    --enable-glamor \",
    "    --enable-suid-wrapper \",
    "    --enable-install-setuid \",
    "    --enable-dri \",
    "    --enable-dri3 \",
    "    --enable-present \",
    "    --enable-xvfb",
    "make"
]

install = [
    "make install"
]
