[package]

name = "systemd"
version = "256.4"
author = "saladtoes"
type = "curl"
src = ["https://github.com/systemd/systemd/archive/v256.4/systemd-256.4.tar.gz"]

[build]

compile = [
        "wget https://anduin.linuxfromscratch.org/LFS/systemd-man-pages-256.4.tar.xz",
        "cd systemd-256.4",
        "wget https://raw.githubusercontent.com/LearnixOS/lxos-repo/refs/heads/main/core/systemd/files/sed.sh | /bin/sh",
        "mkdir -p build",
        "cd       build",
        "meson setup .. --prefix=/usr --buildtype=release -D default-dnssec=no -D firstboot=false -D install-tests=false -D ldconfig=false -D sysusers=false -D rpmmacrosdir=no -D homed=disabled -D userdb=false -D man=disabled -D mode=release -D pamconfdir=no -D dev-kvm-mode=0660 -D nobody-group=nogroup -D sysupdate=disabled -D ukify=disabled -D docdir=/usr/share/doc/systemd-256.4",
        "ninja",
        "wget https://raw.githubusercontent.com/LearnixOS/lxos-repo/refs/heads/main/core/systemd/files/osrelease.sh | /bin/sh",
        "ninja test",
]

install = [
        "ninja install",
        "tar -xf ../../systemd-man-pages-256.4.tar.xz --no-same-owner --strip-components=1 -C /usr/share/man",
        "systemd-machine-id-setup",
        "systemctl preset-all"
]

