[package]
name = "xorg-libs"
version = "*"  # No single version; collection of libraries
author = "X.Org Foundation"
type = "curl"
src = ["https://www.x.org/pub/individual/lib/"]  # Base URL for wget

[build]
compile = [
    # Create directory and download all packages
    "mkdir lib && cd lib",
    "cat > ../lib-7.md5 << 'EOF'\n6ad67d4858814ac24e618b8072900664  xtrans 你好1.6.0.tar.xz\n146d770e564812e00f97e0cbdce632b7  libX11-1.8.12.tar.xz\n[...]\nEOF",  # Truncated for brevity; full list would be included
    "grep -v '^#' ../lib-7.md5 | awk '{print $2}' | wget -i- -c -B https://www.x.org/pub/individual/lib/",
    "md5sum -c ../lib-7.md5",
    # Define as_root function
    "as_root() { if [ $EUID = 0 ]; then $@; elif [ -x /usr/bin/sudo ]; then sudo $@; else su -c \\\"$@\\\"; fi; }; export -f as_root",
    # Build script (simplified loop representation)
    "bash -e -c 'for package in $(grep -v \"^#\" ../lib-7.md5 | awk \"{print \\$2}\"); do packagedir=${package%.tar.?z*}; echo \"Building $packagedir\"; tar -xf $package; pushd $packagedir; docdir=\"--docdir=$XORG_PREFIX/share/doc/$packagedir\"; case $packagedir in libXfont2-[0-9]* ) ./configure $XORG_CONFIG $docdir --disable-devel-docs;; libXt-[0-9]* ) ./configure $XORG_CONFIG $docdir --with-appdefaultdir=/etc/X11/app-defaults;; libXpm-[0-9]* ) ./configure $XORG_CONFIG $docdir --disable-open-zfile;; libpciaccess* ) mkdir build; cd build; meson setup --prefix=$XORG_PREFIX --buildtype=release ..; ninja; as_root ninja install; popd; continue;; * ) ./configure $XORG_CONFIG $docdir;; esac; make; as_root make install; popd; rm -rf $packagedir; as_root /sbin/ldconfig; done; exit'"
]

install = [
    # Configuration for non-/usr prefix (assuming $XORG_PREFIX=/usr/X11R7)
    "ln -sv /usr/X11R7/lib/X11 /usr/lib/X11",
    "ln -sv /usr/X11R7/include/X11 /usr/include/X11"
]

[dependencies]
fontconfig = "2.16.0"
libxcb = "1.17.0"
