[package]

name = "autoconf"
version = "2.72"
author = "GNU"
type = "curl"
src = ["https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz"]

[build]
compile = [
        "./configure --prefix=/usr",
        "make"
]

install = [
    "make install"
    ]
