[package]

name = "fluxbox"
version = "1.3.7"
author = "fluxbox"
type = "curl"
src = ["https://downloads.sourceforge.net/fluxbox/fluxbox-1.3.7.tar.xz"]

[build]

compile = [
	"sed -i '/text_prop.value > 0/s/>/!=/' util/fluxbox-remote.cc",
	"./configure --prefix=/usr",
	"make"
]

install = [
	"make install"
]

