[package]
name = "libcanberra"
version = "0.30"
author = "Lennart Poettering"
type = "curl"
src = [
    "https://0pointer.de/lennart/projects/libcanberra/libcanberra-0.30.tar.xz",
    "https://www.linuxfromscratch.org/patches/blfs/svn/libcanberra-0.30-wayland-1.patch"
]

[build]
compile = [
    "patch -Np1 -i ../libcanberra-0.30-wayland-1.patch",
    "./configure --prefix=/usr --disable-oss",
    "make"
]

[install]
install = [
    "make docdir=/usr/share/doc/libcanberra-0.30 install"
]

[dependencies]
libvorbis = "1.3.7"
