[package]

name = "jinja2"
version = "3.1.4"
author = "saladtoes"
type = "curl"
src = ["https://pypi.org/packages/source/J/Jinja2/jinja2-3.1.4.tar.gz"]

[build]

compile = [
        "pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD",
]

install = [
        "pip3 install --no-index --no-user --find-links dist Jinja2"
]
