[package] 
name = "zlib"
version = "1.3.1"
author = "saladtoes"
type = "curl"
src = ["https://zlib.net/fossils/zlib-1.3.1.tar.gz"]

[build] 
compile = [
        "./configure --prefix=/usr",
        "make"
]
install = [
        "make install",
        "rm -fv /usr/lib/libz.a"
]
