[package]

name = "intltool"
version = "0.51.0"
author = "saladtoes"
type = "curl"
src = ["https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz"]

[build]

compile = [
        "sed -i 's:\\\${:\\\$\\{:' intltool-update.in",
        "./configure --prefix=/usr",
        "make",
]

install = [
        "make install",
        "install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool-0.51.0/I18N-HOWTO"
]
